#+title: Speech présentation
#+author:
#+OPTIONS: toc:nil

* Introduction

** title
Today, I present a method to automatically detect the topological changes caused
by modelling operations on objects.

A topological change is an event which, for example, creates, splits, merges,
topological cells (faces, edges, vertices and so on) within an object.

** slide 1 context
*** animation 1
For example, take the following object

*** animation 2
and subdivide it.

*** animation 3
Faces are split, vertices are created. Nowadays, all modelling APIs detect and
track topological events.

However, detecting these changes means either performing a mesh analysis or
adding code into modeling operations.

In the first case, the operations must first be applied to a given mesh, then
this mesh is analyzed to list the events produced. The detection is fully
automatic. Downside is, the more complex the object, the more expensive the
event detection.

In the second case, a piece of code must be added to the operations and
exhaustively list all the events that will occur. This method of detection is
efficient. Downside is, we can miss events or even mistake them.

Our method is both automatic and cost efficient.

** slide 2 our approach
We propose to formalize the static detection of local events and automate this
process based on an automatic analysis of operations.

To achieve this, we make use of a formalism for objects being the generalized
maps and a formalism for operations being jerboa graph transformation rules.

These analysis make it possible to pre-compute events and localize them.

Doing so reduces the cost of event detection and prevents the addition of code
to operations.

* Transition

I will start presenting the formal tools we use before continuing with our
contribution about the automatic detection of topological events.

* Main concepts
** Generalized maps

*** animation 1
A generalized map is a model allowing us to represent all the cells composing an
object. Consider the following object: a triangle and a quad sharing the edge
BC.
*** animation 2
Firstly, the object is decomposed into faces connected together with a 2-link
(in blue). On the boundaries, the links are forming loops.
*** animation 3
Secondly, faces are decomposed into edges connected together with 1-links (in
red).
*** animation 4
Finally, the edges are decomposed into vertices connected together with 0-links
(in black).

At last, A G-map is a graph whose nodes are called darts and arcs are called
links.

** Transition
In generalized maps, sub-graphs represent cells.

** Orbits

*** animation 1
For example, the face incident to dart "a" contains all the reachable darts
through 0- and 1- links as well as these links.
*** animation 2
Similarly, the edge incident to dart a contains these darts and these 0- and
2-links.
*** animation 3
This edge is a valid <0,2> edge thanks to the loops.
*** animation 4
Here is the vertex incident to "a" with its darts and 1- and 2-links.
*** animation 5
These sub-graphs also generalize the notion of cells. For example, this face
edge of type 0.

An orbit is a sub-graph parameterized with a type "o" corresponding to any set
of dimensions such as those (in red).

** Transition
We are done with the objects' formalism. I will now go on with the formalization
of the operations.

** Jerboa graph transformation rules
*** animation 1
Jerboa is the language we use to represent operations as graph transformation
rules

For example, we will work through the triangulation operation here which matches
the quad face and triangulates it.

*** animation 2
Here is the triangulation rule.
Its left side matches a sub-graph, the right side transforms it into a new one.

*** animation 3
On the left, node n0 matches a <0,1> face. When mapped to dart a0, the quad face
is matched.

The gray parts remain untouched throughout the transformation.

*** animation 4
On the right, n0 is preserved and so are its darts. The node is rewritten from
0,1 to 0 _. That is, the 0-links are preserved and the 1-links are deleted.

*** animation 5
n1 is a created node and so are its darts.

As a created node, n1 is a copy of the left node n0 and matches as many darts.

However, n1 is rewritten from <0,1> to <_,2>.

That is 0 links are not created and 1-links between darts are actually 2-links.

*** animation 5 bis
An explicit 1-link connects n0 and n1 1-to-1.

Subsequently, their respective darts are connected 1-to-1 with 1-links.

*** animation 6
n2 is also a created node.

Unlike n0, n2 is written as 1,2.

Therefore, its darts are connected with 1- and 2-links.

*** animation 6 bis
The values written within nodes are called implicit links.

*** animation 6 ter
These links, between nodes, are called explicit links

*** animation 7
We can define orbits in a generalized maps and we can do so in rules.

Here are the <0,1> face orbits incident to n0.

On the right, the orbit contains n0, n1 and n2 because a 0-link connects n0 and
n1 and an 1-link connects n1 and n2.

*** animation 7 bis
Notice that in this orbit, each node matches both 0- and 1-links.

n0 matches 0 implicitly, 1 explicitly.

n1 matches 1 and 0 explicitly.

n2 matches 0 explicitly and 1 implicitly.

Therefore this face orbit is said to be complete.

Subsequently, the orbit matches complete faces in the object.

More generally, an orbit is said to be complete when each of its node matches
either implicitly or explicitly all the links described in an orbit type.

Lastly, syntactic conditions guarantee the consistency of a generalized map
throughout the application of a rule.

* Transition
Now we reach the heart of our method. I will start with a simple event : the
creation.

* Detecting topological events

** Creation

We continue with the same object and the same rule but this time we study the
creation of this <0,2> edge orbit incident to n1.

This orbit only contains created nodes, that is the orbit is created.

Jerboa rules' syntaxes imposes a created node matches all the possible
dimensions.

Thus this orbit is complete and entirely creates these edges.

All rules are pre-processed with such a syntactic analysis.

In practice no more computing is necessary for this orbit when applying this
rule.

** Transition
Now a more complex event, the split.

** Split
There are two kind of splits: through implicit and explicit links.

*** implicit
Once again, same rule, same object and we go back with the <0,1> face orbit.

In this example, we take interest into this (montrer) second implicit 1-link.

On the right, each node's second implicit link is either deleted or rewritten
into a 2-link.

The orbit is split.

Those 1-links (montrer à gauche) are deleted and you can see (montrer) that no
second implicit link connects darts with neither 0- nor 1-links in the object.

Thus, this orbit (montrer à droite) matches several faces

Additionally, each new face comes from an edge of the former one.

This face has four edges, hence the four faces we see here (montrer).

*** transition

Now we have seen an implicit split, we will see an explicit split.

*** explicit
We now consider a new object: a patch of quads; and a new rule.

This rule disconnects two face edges by cutting their explicit 2-link.

We take interest into this <0,2> edge orbit incident to n0.

Both n0 and n1 matche 0- and 2-links, the orbit is complete.

Cutting the explicit 2-link explicitly splits the orbit in two (montrer règle).
Therefore, the edge is split in the object and the 2-links have become loops
(montrer).


*** false positive split
As a last example, we keep the same object, the same rule but we take interest
into the <1,2> vertex orbit incident to n0.

Here, the rule matches two vertices, one incident to a0 (montrer) the other
incident to b0 (montrer).

Although we study a <1,2> vertex orbit, none of the nodes match a 1-link
(montrer), thus, the orbits are incomplete.

As a result, the matched vertices are only a0,a1 and b0,b1.

This boundary vertex (montrer le sommet de bord) is actually split.

This vertex at the center (montrer), however, is only modified.

There still exists a path between a0 and a1.

Such a situation requires a localized check to verify whether or not two matched
darts belong to the same orbit.

* Transition

We have seen how to detect two topological events, namely the creation and the
split, from Jerboa rules.

* Other events
In the same way, we can compute any other event that can occur while modeling.

Deletion and merging have the inverse properties as respectively the creation
and the split.

Non-modification is when a matched orbit remains unchanged.

The rest is identified as a modification

** Deletion
** Merging
** Non-modification
** Other Modifications

* Conclusion
In order to automatically detect topological changes, we take advantage of the
graph transformation rule formalism on generalized maps to formalize event
detection.

The rules analysis guarantee all the detected event are correctly identified

Combining this formalization with a localization of events allows us to perform
a fully automatic orbit tracking.

It also does not require any code addition within operations.

Another advantage is that most of the analysis is done when pre-computing the
rules.

The rest is done when needed at runtime by checking a localized sub-graph.
