#+title: Speech présentation
#+author:

* Introduction

** title
Today, I present a method to automatically detect the topological changes caused
by modelling operations on objects.

A topological change is an event which, for example, creates, splits, merges,
topological cells (faces, edges, vertices and so on) within an object.

** slide 1 context
*** animation 1
For example, take the following object

*** animation 2
and subdivide it.

*** animation 3
Faces are split, vertices are created. Nowadays, all modelling APIs detect and
track topological events.

However, detecting these changes means performing either a dynamic check or dynamically.

In the dynamic method, the operations must first be applied to a given mesh, then this mesh is analyzed to list the events produced. Downside is, the more complex the object, the more expensive the event detection.

In the static method, a piece of code must be added to the operations and
exhaustively list all the events that will occur. Downside is, it makes more
work and there can be missing or error event detection.

Our approach does combine both static and dynamic detection in order to minimize
detection costs.

** slide 2 our approach
We propose to formalize the static detection of local events and automate this
process based on an automatic analysis of operations.

Doing so, reduces the cost of event detection and prevents the addition of code
to the operations.

* Transition

# First, we use the generalized map's formalism to represent objects.

# Second, we need to formalize the operations with graph transformation rules.

I will start presenting the formal tools we use before continuing with our
contribution.

* Main concepts
** Generalized maps

*** animation 1
A generalized map is a model allowing us to represent all the cells composing an
object. Consider the following object: a triangle and a quad sharing an edge
(the edge BC).
*** animation 2
Firstly, the object is decomposed into faces connected together with a 2-link
(in blue). On the boundaries, the links are forming loops.
*** animation 3
Secondly, faces are decomposed into edges connected together with 1-links (in
red).
*** animation 4
Finally, the edges are decomposed into vertices connected together with 0-links
(in black).

At last, A G-map is a graph whose vertices are called darts and arcs are called
links.

** Transition
In generalized maps, sub-graphs represent cells.

** Orbits

*** animation 1
For example, the face incident to dart "a" contains all the reachable darts
though 0- and 1- links as well as these links.
*** animation 2
Similarly, the edge incident to dart a contains these darts and these 0- and
2-links.
*** animation 3
This orbit is a valid 0,2 edge thanks to the loops.
*** animation 4
Here is the vertex incident to a with its darts and 1- and 2-links.
*** animation 5
Orbit also generalize the notion of cells. For example, this face edge of
type 0.

An orbit is parameterized with a type "o" that can correspond to any set of
dimensions such as these.

** Transition
We are done with the objects' formalism. I will now go on with the formalization
of the operations.

** Jerboa graph transformation rules
*** animation 1
Jerboa is the language we use to represent operations as graph transformation
rules

For example, we will work through the triangulation operation here which matches
the quad face and replaces it with a several triangles.
*** animation 2
Here is the triangulation rule.
Its left side matches a sub-graph, the right side transforms it into a new one.

*** animation 3
The left side matches a <0,1> face, when the node n0 is mapped to dart a0, the
quad face is matched.

For your information, the gray parts remain untouched throughout the
transformation.

*** animation 4
On the right, n0 is preserved and so are its darts. The node is rewritten from
0,1 to 0 _. That is, the 0-links are preserved and the 1-links are deleted.

*** animation 5

n1 is created and is a copy of the left hand side node n0.

n1 creates and matches as much darts as n0. However, in n1, 0 is rewritten into
an underscore and 1 is rewritten into a 2. Subsequently, n1's darts are
connected together with 2-links only.

nodes n1 and n0 are connected 1-to-1 with a 1-link. Subsequently, their
respective darts are connected 1-to-1 with 1-links.

*** animation 6
n2 is also a created node. Unlike n0, it is written as 1,2. Therefore, its darts
are connected with 1-links instead of 0-links and 2-links instead of 1-links.

The values written within nodes are called implicit links.

These links, between nodes, are called explicit links
*** animation 7
While we can define orbits in a gmap, we can do so in rules. Here are the face
orbits incident to n0 and their matches before and after the application.

Moreover, an orbit is said to be complete when each of its node matches either
implicitly or explicitly all the links described in an orbit type.

For example, on the left, the face orbit matches both 0 and 1 links.

Lastly, there are syntactic conditions guaranteeing that a G-map remains a G-map
after the application of a rule.

* Transition
Now we reach the heart of our method. I will start with a simple event : the
creation.

* Detecting topological events

** Creation
Here, the edge orbit only contains created nodes therefore the orbit is created.

By Jerboa syntactic conditions a created node matches all the possible
dimensions and a created orbit is necessarily complete.

Therefore, since the edge orbit created in the rule is complete, the edges it
matches in the gmap are created.

When starting a modeler, all rules are pre-processed with such a syntactic
analysis. This allows a static detection of all occurring events at the moment a
rule is applied.

** Transition
Now a more complex event, the split.

** Split
There are two kind of splits: implicit and explicit.
*** implicit

In the right-hand side of the rule, the face orbit's second implicit links are
either deleted or rewritten from 1 to 2. Therefore, the orbit is split
through implicit 1-links in the rule.

The right-hand side matches exactly four faces because there is neither 0- nor
1-links to connect them (otherwise there wouldn't be any split).

Additionally, each new face comes from an edge of the former (one). This face has four
edges, hence the four faces we see here.

*** explicit
Now consider the rule that disconnects two face edges by cutting their 2-links
and a new object being a patch of quads.

Here we expect to split the edge incident to a0 by cutting its 2-links

In the right-hand side, the explicit 2-link between n0 and n1 is replaced by one
2-loop for each of them. The orbit is split in two and, therefore, the matched
edge in the gmap is also split in two.

Since the edge orbit is complete in the rule, no further verification is needed.

*** false positive split
Now, for a vertex orbit, we may expect two splits.

# We have one orbit on the left and two on the right.

Yet, the orbit is incomplete, all of its nodes miss a 1-link.

See, even though the vertex on the right is split, the one at the center
is only modified.

Such situation requires a localized dynamic check to verify whether or not two
matched darts belong to the same orbit.

* Transition

We have seen how to detect two topological events, namely the creation and the
split, from Jerboa rules.

* Other events
We can do it for more even events.
** Deletion
** Merging
** Modification
** Non-modification

* Conclusion
In order to automatically detect topological changes, we take advantage of
generalized maps to model objects and graph transformation rules to formalize
modelling operations.

These formalisms allow us to syntactically analyse rules instead of code. Furthermore, its prevents the need to add specific code instruction within operations.

Another advantage is the possibility to pre-compute the rules for a static
detection and dynamically check a localized sub-graph when needed.
