#+title: Speech présentation
#+author:
#+OPTIONS: toc:nil

* Introduction

** title
Today, I present a method to automatically detect the topological changes caused
by modelling operations on objects.

A topological change is an event which, for example, creates, splits, merges,
topological cells (faces, edges, vertices and so on) within an object.

** slide 1 context
*** animation 1
For example, take the following object

*** animation 2
and subdivide it.

*** animation 3
Faces are split, vertices are created. Nowadays, all modelling APIs detect and
track topological events.

However, detecting these changes means performing either a dynamic check or dynamically.

In the dynamic method, the operations must first be applied to a given mesh, then this mesh is analyzed to list the events produced. Downside is, the more complex the object, the more expensive the event detection.

In the static method, a piece of code must be added to the operations and
exhaustively list all the events that will occur. Downside is, it makes more
work and there can be missing or error event detection.

Our approach does combine both static and dynamic detection in order to minimize
detection costs.

** slide 2 our approach
We propose to formalize the static detection of local events and automate this
process based on an automatic analysis of operations.

To achieve this, we make use of formalism for objects being the generalized maps
and a formalism for operations being jerboa graph transformation rules.

Doing so, reduces the cost of event detection and prevents the addition of code
to the operations.

* Transition

# First, we use the generalized map's formalism to represent objects.

# Second, we need to formalize the operations with graph transformation rules.

I will start presenting the formal tools we use before continuing with our
contribution about the automatic detection of topological events.

* Main concepts
** Generalized maps

*** animation 1
A generalized map is a model allowing us to represent all the cells composing an
object. Consider the following object: a triangle and a quad sharing an edge
(the edge BC).
*** animation 2
Firstly, the object is decomposed into faces connected together with a 2-link
(in blue). On the boundaries, the links are forming loops.
*** animation 3
Secondly, faces are decomposed into edges connected together with 1-links (in
red).
*** animation 4
Finally, the edges are decomposed into vertices connected together with 0-links
(in black).

At last, A G-map is a graph whose vertices are called darts and arcs are called
links.

** Transition
In generalized maps, sub-graphs represent cells.

** Orbits

*** animation 1
For example, the face incident to dart "a" contains all the reachable darts
though 0- and 1- links as well as these links.
*** animation 2
Similarly, the edge incident to dart a contains these darts and these 0- and
2-links.
*** animation 3
This orbit is a valid 0,2 edge thanks to the loops.
*** animation 4
Here is the vertex incident to a with its darts and 1- and 2-links.
*** animation 5
Orbit also generalize the notion of cells. For example, this face edge of
type 0.

An orbit is parameterized with a type "o" that can correspond to any set of
dimensions such as those (in red).

** Transition
We are done with the objects' formalism. I will now go on with the formalization
of the operations.

** Jerboa graph transformation rules
*** animation 1
Jerboa is the language we use to represent operations as graph transformation
rules

For example, we will work through the triangulation operation here which matches
the quad face and replaces it with a several triangles.
*** animation 2
Here is the triangulation rule.
Its left side matches a sub-graph, the right side transforms it into a new one.

*** animation 3
The left side matches a <0,1> face, when the node n0 is mapped to dart a0, the
quad face is matched.

For your information, the gray parts remain untouched throughout the
transformation.

*** animation 4
On the right, n0 is preserved and so are its darts. The node is rewritten from
0,1 to 0 _. That is, the 0-links are preserved and the 1-links are deleted.

*** animation 5

n1 is created and is a copy of the left hand side node n0.

n1 creates and matches as much darts as n0. However, in n1, 0 is rewritten into
an underscore and 1 is rewritten into a 2. Subsequently, n1's darts are
connected together with 2-links only.

nodes n1 and n0 are connected 1-to-1 with a 1-link. Subsequently, their
respective darts are connected 1-to-1 with 1-links.

*** animation 6
n2 is also a created node. Unlike n0, it is written as 1,2. Therefore, its darts
are connected with 1-links instead of 0-links and 2-links instead of 1-links.

The values written within nodes are called implicit links.

These links, between nodes, are called explicit links
*** animation 7
While we can define orbits in a gmap, we can do so in rules. Here are the face
orbits incident to n0.

Notice that in this orbit, each node matches both 0- and 1-links, n0 matches 0
implicitly, 1 explicitly, n1 matches 1 and 0 explicitly and n2 matches 0
explicitly and 1 implicitly. Therefore the orbit is said to be complete.

Subsequently, the orbit matches complete faces in the gmap

More generally, an orbit is said to be complete when each of its node matches
either implicitly or explicitly all the links described in an orbit type.

Lastly, syntactic conditions guarantee the consistency of a generalized map
throughout the application of a rule.

* Transition
Now we reach the heart of our method. I will start with a simple event : the
creation.

* Detecting topological events

** Creation

We continue with the same object and the same rule but this time we study the
creation of this <0,2> edge orbit incident to n1 and these edges.

This orbit only contains created nodes, that is the orbit is created.

Jerboa rules' syntaxes imposes a created node matches all the possible
dimensions.

Thus this orbit is complete and entirely creates these edges.

All rules are pre-processed with such a syntactic analysis. In practice no more
computing is necessary for this orbit when applying this rule.

** Transition
Now a more complex event, the split.

** Split
There are two kind of splits: through implicit and explicit link.
*** implicit

Once again, same rule, same object and we go back with the <0,1> face orbit.

In this example, we take interest into this (montrer) second implicit 1-link. On
the right, each node's second implicit link is either deleted or rewritten into
a 2-link.

Those 1-links (montrer à gauche) are deleted and you can see (montrer) that no
second implicit link connects darts with either 0- or 1-links in the object

Thus, this orbit (montrer à droite) matches several faces

Additionally, each new face comes from an edge of the former (one). This face has four
edges, hence the four faces we see here (montrer).

*** transition

Now we have seen an implicit split, we will see an explicit split.

*** explicit
We now consider a new object: a patch of quads; and a new rule. The rule
disconnects two face edges by cutting their explicit 2-link.

We take interest into this <0,2> edge orbit incident to n0.
As in previous slide, the orbit is complete.

Cutting the explicit 2-link explicitly splits the orbit in two (montrer règle).
Therefore, in the object, the edge is split and the 2-links have become loops
(montrer).


*** false positive split
As a last example, we keep the same object, the same rule but we take interest
into the <1,2> vertex orbits in the rule.

To split an edge means to also split their vertices. Here, the rule matches two
vertices, one incident to a0 (montrer) the other incident to b0 (montrer).

However, we study of <1,2> vertex orbit and none of the node matches a 1-link
(montrer), thus, the orbits are incomplete. As a result, the matched vertices
are a0,a1 and b0,b1.

(montrer l'objet de droite) This boundary vertex (montrer le sommet de bord) is
actually split. This vertex at the center (montrer), however, is only
modified. As you can see, there still exist a 1-2-path in the object between a0
and a1.

Such situation requires a localized dynamic check to verify whether or not two
matched darts belong to the same orbit.

* Transition

We have seen how to detect two topological events, namely the creation and the
split, from Jerboa rules.

* Other events
In the same way, we can compute any other event that can occur while modeling.
Deletion and merging have the inverse properties as respectively the creation and the split.
Non-modification is when a match orbit remains unchanged

** Deletion
** Merging
** Non-modification
** Other Modifications

* Conclusion
In order to automatically detect topological changes, we take advantage of the
graph transformation rule formalism on generalized maps to formalize event
detection.

This guarantees all detected event are correctly identified

Combining this formalization with a localization of events allows us to perform
a fully automatic orbit tracking.

Rule analysis do not require any code addition within operations.

Another advantage is that most of the analysis is done when pre-computing the
rules. The rest is done when needed at runtime by checking a localized
sub-graph.
