#+title:
#+date:
#+author:
#+options: toc:nil

* Poster highlight speech

Re-evaluation mechanisms are, nowadays, made available in most professional grade
CAD softwares allowing users to generate variations of an object by editing 
operations' parameters. 

Nowadays, most existing methods require tracking numerous topological entities.

Moreover, the re-evaluated operation sequence is not modified, only their
parameters can be changed.

On the contrary, our method only tracks the topological entities used as
parameters in operations.

It also allows the user to edit the operation sequence by adding, deleting or
moving some operations. And operations' parameters can still be changed.

To achieve this, we use a formalisation of operations as graph transformation
rules.

During the initial evaluation, we only register the histories for the elementary
entities of the object.

Then we use the rule analysis I presented earlier today to detect topological events.
Thanks to these detections we can re-compute the topological parameter histories.

After editing the operation sequence, and during its execution, we update the
topological parameter histories in order to take into account the new
topological events.

Finally, we can match the new topological parameters within the object.

Topological parameter histories of both the initial evaluation and re-evaluation
are represented using Directed Acyclic Graphs to model splits or merges of
topological cells.

In addition, we have different ways to exploit this Directed Acyclic Graph of
topological cell evolution. Each way correspond to a specific strategy allowing
matching new topological parameters.

The nitty-gritty is quite complicated without the adequate figures but I will be
pleased to explain you with help of my poster.

# exploiting this re-evaluation DAG gives the ability  strategies such
# as, applying the same operation onto each subdivisions of a cell.
