#+title:
#+date:

Pour répondre à la problématique du référencement d'un élément géométrique,
Cascaval et al. (2023) affirment qu'un outil de CAO doit répondre à trois
propriétés :
- le référencement doit être continu par rapport aux paramètres des opérations,
- la géométrie à référencer doit pouvoir être sélectionnée parmi un ensemble
  d'éléments,
- l'utilisateur pouvoir contraindre la production finale à certaines classes de topologie.

Sont également posés les concepts suivants :
- Un modèle paramétrique est un programme.
- Un élément géométrique est une donnée construite dans le programme.
- Une référence est le résultat d'une requête sur un élément géométrique.
- Les types géométriques sont les point, segment (ligne ou courbe), polygone
  (conceptuellement une face sans trou) et face (un élément produit à partir
  d'un ou plusieurs polygones).

Ainsi, les auteurs proposent un langage spécifique à la conception de modèles
paramétriques mettant en œuvre un suivi des éléments géométriques dont les
historiques sont enrichis par une sémantique détaillée pour la généalogie des
éléments (\textit{semantics for fine-grained element lineage}). Ainsi, trois
types de relations entre un élément en entrée et en sortie d'une opération sont
définis : la relation de transformation, de sous-ensemble et de dérivation.

La relation de transformation établie un lien directe entre un élément en entrée
et en sortie à travers une opération. En effet, les opérations telles que la
rotation et la translation ne créent rien de nouveau que ce soit en termes de
géométrie ou de topologie. Seuls les paramètres géométriques (grandeur,
position, …) sont modifiés.

La relation de sous-ensemble établie un lien entre un ensemble d'éléments en
entrée d'une opération et un élément en sortie. Il s'agit, typiquement dans les
opérations de CSG, de faire le lien entre, par exemple deux arêtes qui
s'intersectent et un sommet résultat de cette intersection.

La relation de dérivation, elle, établie plusieurs liens entre de la géométrie
existante et de la géométrie nouvellement créée. Prenons le cas du chanfrein sur
un sommet présenté par les auteurs. Lorsque l'opération de chanfrein est
appliquée, une arête est créée à partir d'un sommet, il s'agit du premier lien
établi. Il faut ensuite faire la distinction entre les deux sommets aux
extrémités de cette arête. Pour cela, la relation de dérivation établit un lien
entre l'un des deux sommets une arête adjacente pré-existante.
