#+title:
#+date:

Pour Cascaval et al., un langage conçu pour la CAO doit respecter trois
propriétés :
- il ne doit pas introduire de discontinuité dans le référencement d'une
  géométrie,
- il doit permettre la sélection de tout ou partie d'un ensemble d'éléments
  géométrique résultant de la partition d'une géométrie passée en entrée d'une
  opération,
- l'utilisateur doit pouvoir exclure des configurations topologiques des modèles
  en sortie du programme.

Dans Cascaval (2023), les auteurs placent leurs travaux dans un contexte défini
par les concepts suivants :
- Un modèle paramétrique est un programme.
- Une référence est le résultat d'une requête sur un élément géométrique.
- Les types géométriques sont les point, segment (ligne ou courbe), polygone
  (conceptuellement une face sans trou) et face (un élément produit à partir
  d'un ou plusieurs polygones).

Ainsi, les auteurs proposent un langage spécifique à la conception de modèles
paramétriques en 2.5D mettant en œuvre un suivi des éléments géométriques dont les
historiques sont enrichis par une sémantique détaillée pour la généalogie des
éléments (\textit{semantics for fine-grained element lineage}). Ainsi, trois
types de relations entre un élément en entrée et en sortie d'une opération sont
définis : la relation de transformation, de sous-ensemble et de dérivation.

La relation de transformation établie un lien directe entre un élément en entrée
et en sortie à travers une opération. En effet, les opérations telles que la
rotation et la translation ne créent rien de nouveau que ce soit en termes de
géométrie ou de topologie. Seuls les paramètres géométriques (grandeur,
position, …) sont modifiés.

La relation de sous-ensemble établie un lien entre un ensemble d'éléments en
entrée d'une opération et un élément en sortie. Il s'agit, typiquement dans les
opérations de CSG, de faire le lien entre, par exemple deux arêtes qui
s'intersectent et un sommet résultat de cette intersection.

La relation de dérivation, elle, établie plusieurs liens entre de la géométrie
existante et de la géométrie nouvellement créée. Prenons le cas du chanfrein sur
un sommet présenté par les auteurs. Lorsque l'opération de chanfrein est
appliquée, une arête est créée à partir d'un sommet, il s'agit du premier lien
établi. Il faut ensuite faire la distinction entre les deux sommets aux
extrémités de cette arête. Pour cela, la relation de dérivation établit un lien
entre l'un des deux sommets une arête adjacente pré-existante.



Ici, Cascaval et al. proposent un langage permettant de créer des modèles
paramétriques respectant des contraintes à la fois topologiques et géométriques
tout en assurant que la géométrie passée en référence respecte les intentions de
modélisations telles que définies par l'utilisateur. Néanmoins, en l'état actuel, les
