#+title:
#+author:
#+options: toc:nil

* page de titre
- Merci Madame la présidente, chers membres du jury, cher auditoire, c'est avec
  un grand plaisir que je vais vous présenter mes travaux de thèse, intitulés «
  modélisation et rejeu basés sur des règles » qui ont été encadrés par Agnès
  Arnould, David Marcheix, Xavier Skapin et Stéphane Jean.

+ Ces travaux s'inscrivent dans le domaine de la modélisation géométrique.

* modélisation géométrique
- Au cœur de ce domaine se trouvent les logiciels permettant de modéliser des
  objets en 2D ou 3D.
- Ces modeleurs sont utilisés pour de nombreuses applications qui touchent au
  quotidien de chacun d'entre nous.
- À titre d'exemple, ces logiciels sont utilisés pour :
  - aménager des espaces en intérieur.
  - concevoir et créer du mobilier ou
  - créer et faire du rendu pour des scènes d'animation utilisées dans des films
    ou jeux vidéos.

+ Certains domaines d'application nécessitent une approche interactive de la
  modélisation, c'est-à-dire une approche où l'utilisateur va pouvoir tester
  différentes variations de l'objet qu'il est en train de modéliser.

* domaines d'applications
- Par exemple, en archéologie, les fouilles effectuées sur un bâtiment ne
  fournissent généralement que des éléments partiels pour permettre sa
  reconstruction tel qu'il était à une période donnée.
- Dans cet exemple, les fouilles n'ont révélé que les quelques artefacts à
  gauche, en rouge.
- Une problématique pour l'archéologie est donc d'établir des hypothèses de restitutions à partir de ces artefacts.
- Par exemple, ces deux illustrations sont deux hypothèses de restitution d'un
  même bâtiment.
- Les hypothèses sont donc bien des variations d'une même construction.

- Comme autre exemple, en conception assistée par ordinateur (ou CAO), de
  nombreuses pièces mécaniques partagent le même processus de construction.
- Elles ne varient que par certaines propriétés géométriques comme le rouage
  vert (à droite) qui est simplement plus petit que le jaune.
- Il est donc important de pouvoir construire différentes variations d'une même
  pièce.

- En pratique, nous allons voir comment ces variations sont générées dans les
  modeleurs usuels et les limites que cela pose.

* modélisation paramétrique
- La création de variation d'un même objet se base sur la notion de modélisation
  paramétrique.
- Elle se compose de 3 étapes :
  - La construction d'un objet en définissant, via des paramètres, ses
    propriétés géométriques et topologiques
  - L'édition du processus de construction aussi appelé spécification
    paramétrique en modifiant les paramètres de l'objet.
  - Le rejeu de la spécification paramétrique éditée

- Même si ce processus semble simple, il pose de nombreux problèmes et notamment
  celui de la nomination persistante adressée dans nos travaux.
- Nous allons l'illustrer avec un exemple simple.

* problématique de la nomination persistante
# - On commence par construire l'objet qui correspond à la spécification
# paramétrique (à droite)
- Supposons que nous construisons, à gauche, un objet à l'aide de cette
  spécification paramétrique (à droite).
- La première opération crée la face f1 dont son arête e1.
- L'opération suivante crée la face f2 à partir de e1.
- La triangulation scinde f2 en plusieurs faces dont f7.
- Enfin, f7 est coloriée.

- Nous voulons créer une variation de cet objet en ajoutant une opération dans
  la spécification.

- Au rejeu, on a toujours notre face carrée f1.
- L'opération ajoutée scinde l'arête e1 en e5 et e6
- L'extrusion crée les faces f3 et f4 à partir de e3 et e4.
- Et maintenant les faces f2 et f7 n'existent plus.
- Comment, alors, appliquer les opérations suivantes qui ont besoin de ces faces
  ?
- Une solution possible serait de trianguler f3 et f4 puisqu'elles sont
  construites comme f2.
- Nous voyons donc, sur cet exemple, le besoin d'un nom persistant pour
  identifier les cellules par leurs historiques d'évolution.

- Pour ce problème, nos travaux s'intéressent à trois questions :
  - l'identification des changements dans la topologie (évènements)
  - le rejeu
  - et les stratégies pour adapter le rejeu

* plan 1

- Voyons maintenant le plan pour le reste de cette présentation
- Tout d'abord, je vous propose de compléter cette introduction avec un bref
  état de l'art.
- Je vais ensuite présenter les formalismes que nous utiliserons pour nos
  contributions.
- Je poursuivrai avec nos contributions sur la détection des évènements, le
  développement d'un mécanisme de rejeu et son extension à tout type
  d'opération.
- Enfin, je conclurai cette présentation et proposerai différentes perspectives
  de travaux futurs.

* État de l'art
- Dans la littérature concernant le rejeu et la nomination persistante, nous
  pouvons identifier un certain nombre de concepts communs à différentes
  approches.

- Le premier concerne le type d'édition étudié.
- La plupart des approches se limitent à l'édition des paramètres géométriques.
- Ils étudient la problématique de la nomination dans ce contexte où seuls les paramètres géométriques peuvent modifiés.

- Dans cet exemple, nous pouvons voir un tube pneumatique avec à droite ses
  paramètres géométriques qui sont les seuls éléments éditables.

- Pourtant, au-delà de l'édition des paramètres géométriques, l'édition des
  opérations, c'est-à-dire l'ajout, la suppression, le déplacement d'une
  opération n'est pas sans effet sur la problématique de la nomination.
- Seules les approches de Cardot et Cascaval prennent en compte ce type
  d'édition.

- Le deuxième concept concerne la construction de l'historique d'une cellule.
- Toutes les approches nécessitent de suivre, d'une manière ou d'une autre, l'évolution de certaines cellules (illustration, montrer graphe).
- Mais nous observons deux choses :
  - D'une part, l'histoire d'une cellule est systématiquement représentée de
    façon partielle, c'est-à-dire en ne représentant qu'une partie des cellules
    impliquées dans son histoire. (graphe)
  - D'autre part, la construction de cet historique nécessite de pouvoir calculer l'évolution des cellules à chaque étape de modélisation.
  - Ce calcul est, la plupart du temps, réalisé de façon globale via un journal de bord qui permet, à chaque étape de modélisation, de tracer l'évolution de chaque cellule du modèle.
  - Mais ce calcul peut aussi, dans un certain nombre de cas, être réalisé
    manuellement en étant codé directement dans les opération (comme le propose
    Cascaval) ou fourni explicitement par le concepteur de l'opération (comme le
    propose Cardot).


- Dans cet exemple, le graph, en haut à droite, montre la création de toutes les
  faces de cet objet et l'on peut voir chacune des faces issues de la
  triangulation sans moyen de les distinguer.
- En bas à droite, chacune des faces obtiennent le même nom à partir de la face
  scindée, ce qui n'aide pas non plus à les distinguer.

- À notre connaissance, aucune approche ne propose aujourd'hui d'historique qui
  soit complet et dont le calcul est à la fois local et générique.

- Un troisième concept est celui de la nomination d'une cellule.
- Cette nomination est généralement basée sur les faces du voisinage topologique
  et impose de définir un schéma de nomination différent pour chaque type de
  cellule et n'est donc pas homogène.

- Dans cet exemple, on peut voir deux arêtes nommées d'après leur faces
  incidentes et les faces à leurs extrémités.
- Un sommet sera nommé uniquement nommé par ses trois faces incidentes.

- L'essentiel des approches utilisent les faces, car simples à caractériser en
  2D et 3D.
- Néanmoins, aucune de ces approche ne propose de schéma de nomination qui soit
  homogène, c'est-à-dire le même pour tous les types de cellules.

- Le quatrième concept est la dimension de modélisation proposée par un modeleur
  qui est généralement fixé en 3D.

- Dans cet exemple, nous avons un ensemble d'objets en 2.5D construits par
  Cascaval et al.

- Enfin, le cinquième concept est le type d'opérations traitées par un modeleur.
- La quasi-totalité des modeleurs permet d'utiliser tout type d'opérations, à
  l'exception de Cardot et al. qui ne proposent de traiter qu'un ensemble réduit
  d'opérations.

- Au travers de cet état de l'art, 4 points nous apparaissant comme limitant
  dans la modélisation paramétrique :
  + L'édition des spécifications paramétriques qui concerne, très
    majoritairement, uniquement la modification de paramètres géométriques
  + Les approches actuelles ne sont pas capables de représenter complètement les
    historiques des cellules et laissent ainsi de la place à l'ambiguïté lors de
    l'identification.
  + De plus, toujours pour les historiques, aucune des approches proposées
    n'effectue de calcul qui soit à la fois local et générique.
  + Enfin, aucun des modeleurs existant n'apporte la flexibilité nécessaire pour
    construire des modèles génériques en dimension

* Plan 2
- Au travers de cet état de l'art, nous avons donc identifié 4 objectifs:
  - l'édition complète d'une spécification comprenant l'ajout, la suppression et
    le déplacement d'opérations
  - la construction d'historiques complets pour le suivi des évolutions de
    cellules
  - le développement d'une méthode locale et générique pour créer ces
    historiques
  - enfin, l'implantation d'un modeleur capable de modéliser des objets
    génériques en dimension.

- Pour mener à bien ces objectifs, nous utilisons trois formalismes :
  - un pour les objets, avec les cartes généralisées
  - un pour les opérations avec les règles Jerboa
  - enfin, un pour les changements topologiques.

- Nos travaux donnent lieu à 3 contributions :
  - la première est la formalisation des changements topologiques sur les
    cellules et est au cœur de nos travaux
  - la deuxième est le développement des mécanismes nécessaires au rejeu dans un
    système de modélisation basé sur les règles Jerboa et, enfin,
  - l'extension de notre modeleur à tout type d'opérations.

* Plan 6

- Nous arrivons maintenant à notre troisième contribution.
- Celle-ci concerne l'extension de notre système de rejeu à tout type
  d'opération.

* Scripts de règles
- Les règles Jerboa permettent de représenter une grande variété d'opérations de
  modélisation.
- Toutefois, elles ne permettent pas d'utiliser les structures de contrôle usuelles, c'est-à-dire les boucles et les alternatives.
- Pour cela, Jerboa propose un langage de script comme celui-ci qui permet de
  déconnecter un volume de sa composante connexe.
- L'opération est composée :
  - d'une part d'un graphe qui spécifie l'entrée et la sortie du script
  - d'autre part


* Scripts de règles
- règles -> opérations limités -> pas de structure de contrôle
- exemple scripts qui découd un volume d'une composante connexe
- opérations en deux partie :
  - partie graphe -> entrée sortie
  - partie code de l'opération
  - Pour chaque face du volume
    - Si la face est connectée à un autre volume
      - Alors on découd les 3-liaisons de cette face
- trois structures de contrôle :
  - séquence
  - itération de sous-orbites
  - alternative

* Séquence
- commencer avec séquence
- exemple extrude une face en un ruban
- séquence -> pas de difficulté particulière
- se pose la question de la représentation
- exemple
  - option 1 : représentation boîte fermée
    - application du script sur le brin 5
    - coloration de la face brin 31
    - rien à faire
    - construction explicite de la sortie par les développeurs
  - option 2 : représentation boîte ouverte -> on choisit cette option
    - séquence comme une spécification -> accès aux opérations
    - représentation pas à pas des opérations avec paramètres
    - nom persistant montre opérations dans script
  - affichage du script dans le DAG -> trace évolution paramètre qui conditionne
    application script -> flèche verte
  - rejeu : ajout d'un sommet sur l'arête extrudée
  - tout se passe à l'identique, en 2 fois, parce que split donc deux affichages
    de la boîte

* Itération
- deuxième structure de contrôle : itération càd une boucle qui parcourt des sous-orbites
- dans cet exemple, ce script parcourt chacune des faces d'une composante
  connexe et la triangule
- pour l'itération 1 seul ajout :
  - dans la spec : enregistrement de l'orbite à itérer comme paramètre
  - dans le DAG : une boîte FOR avec deux flèche verte :
    - une pour l'orbite d'itération qui conditionne l'entrée dans la boucle (montrer branche et spec)
    - une pour l'instance (montre branche et spec) qui conditionne la ré-application de la ou des
      opérations dans la boucle
- au rejeu on ajoute une opération qui contracte (supprime) une arête
- la face qui avait pour origine cette arête n'est pas recréée
- donc pas de coloration
- cependant on a fusion des sommet et une seule application
- donc pas de triangulation sur-numéraire

* Alternative
- troisième structure de contrôle : alternative car application d'une opération ou d'une autre si une condition précise est rencontrée
- dans cet exemple, ce script regarder si une face est un carré ou triangle
- si carré ALORS la face est triangulée
- SINON (si déjà carrée), alors on insère une face au milieu
- À gauche exemple de jeu initial
- création d'une face carrée -> le script triangule -> chanfrein du sommet central
- À droite exemple de rejeu
- contraction d'arête -> face entrée triangle -> le script insère une face -> chanfrein de trois sommets
- rien de nouveau côté DAG
- par contre -> nécessité d'identifier les évènements similaires entre opération then et opération else
- Dans cet exemple, on identifie ce sommet comme étant l'orbite encadrée en jaune, celle-ci est créée.
- dans la règle alternative -> orbite encadrée désigne les sommets créés
- ces trois sommets, tous créés, seront donc proposés à l'utilisateur pour ré-appliquer le chanfrein
- on peut faire ça pour tous les évènements, comme ici avec les faces scindées.
