#+title: Plan détaillé du manuscrit et avancement
#+language: fr

*  Intro
*  État de l'art
Ici, je présente en deux temps l'état de l'art de la réévaluation dans les systèmes de modélisation paramétrique.
Première étape, on a la modélisation à base de règle (Il y a plusieurs systèmes de modélisation qui existent, je restreins rapidement sur la modélisation à base de règles)
Deuxième étape, on a l'état de la réévaluation dans les systèmes de modélisation paramétriques (réévaluation que l'on étend aux systèmes à base de règles de transformation de graphe)
** Modélisation à base de règles
Ici, je présente les concepts et outils utilisés en modélisation à base de règle.
L'objectif est de présenter les outils *qui sont essentiels pour la définition de concepts tout au long du manuscrit*

Dans cette section, je reprends l'essentiel des concepts (hors suivi d'orbite) défini dans le document de formalisation.
J'ajoute aussi une présentation rapide des scripts de règles pour les aborder plus tard dans le chapitre qui parlera des scripts de règles
*** Rappels sur les graphes
Tout d'abord, il y a des rappels sur les fondamentaux, ce que sont des graphes (topologiques) et ce qui en découle.
- Graphe
- Notions ensemblistes sur les graphes (pour définir les sous-graphes et autres)
- Sous-graphe
- Chemins
*** G-carte : Lienhardt, Damiand
Je présente les G-cartes et ce qui en découle.
- G-carte
- Orbite
*** Règles de transformation de graphe : Belhaouari, Arnould
Je présente les règles en commençant avec les règles instanciées pour remonter jusqu'aux règles et scripts Jerboa.
- Concepts (morphismes, union disjointe tels que présentés dans le doc de formalisation avec des exemples visuels)
- Règles instanciées de transformation de graphe (pour donner idée)
- Règles Jerboa de transformation de graphe
  - règles « repliées » (J'explique que dans ce manuscrit, on ne traitera que les règles dites repliées)
- Scripts de règles Jerboa : Gauthier
** Modélisation paramétrique
Dans cette section, je fais un état autour de la modélisation paramétrique.
Mentionner rapidement les types de modèles paramétriques et dire que dans ce manuscrit, on s'intéresse aux modèles paramétriques fonctionnels
*** Concepts, définitions et propriétés
**** Modèle paramétrique fonctionnel
Définition et présentation *rapide* de ce qu'est un modèle paramétrique fonctionnel.
Définition et présentation d'une spécification paramétrique (une définition ~légère~ sera probablement donnée en chapitre d'introduction mais on verra bien)
Dans quels cadres les modèles paramétriques sont utilisés
**** Problématique lors de certains cas d'usages (réévaluation, transfert de modèles, …)
Présentation de la problématique de l'identification persistante de cellules topologiques (plus coquilles, géométrie…) lors du transfert/de la réévaluation d'un modèle.
**** Nomination persistante : définitions et propriétés
Définition et présentation du concept de nommage persistant
Définitions des concepts développés pour le nommage persistant
**** Critères de classification des systèmes de modélisation
Présentation d'une classification des systèmes de nommage persistant
*** Approches de réévaluation existantes en CAO (Kripac, Capoyleas, Chen, Mun, Wu, Cheon, Fajarna, Agbodan, Marcheix, Hepworth, Cardot …)
Positionner les approches selon les critères établis issus principalement de la
CAO, conception pièces mécaniques + conception bâtiments (reprendre ce qui a été
fait).
*** Systèmes de réévaluation existants (une par auteur)
À venir
*** Réévaluation à base de règles (Cardot)
Reprendre les contributions et nouveautés apportées avec la thèse d'Anaïs Cardot.
Aborder les limitations pour faire le lien plus tard avec ma thèse

*  Formalisation des évènements (suivi)
Pour être en mesure de proposer un nommage persistant avec une histoire riche et
complète des entités topologiques d'un objet, il faut suivre l'évolution de ces
entités topologiques.
#
Les méthodes existantes proposent de faire cela soit en suivant
explicitement toutes les cellules d'un type donné, soit en le codant
directement dans les opérations, voire, un mix des deux.
#
Ici, je présente la première partie de mes travaux : proposer un suivi des cellules grâce à l'analyse statique des règles de modélisation.
** Introduction
notions de suivi et d'origine dans un exemple ; extraction automatique en pré-calcul grâce à l'analyse des règles
** Les évènements dans les transformations d'objets (suivi)
Ici, je présente le suivi des évènements d'un point de vue ensembliste dans un objet
*** la création
*** la suppression
*** le non-changement
*** la modification
*** la scission
*** la fusion
*** le sans effet / NOEFFECT
** Les évènements dans les règles de transformation de graphe (suivi)
Ici, je présente le suivi des évènements du point de vue des règles instanciées.
*** la création
*** la suppression
*** le non-changement
*** la modification
*** la scission
*** la fusion
*** le sans effet
** Les évènements dans les règles Jerboa (suivi, origine et chemins)
Ici, je présente le suivi des évènements du point de vue des règles Jerboa. Ces
règles présentent l'avantage de définir implicitement des relations que l'on
peut extraire avec une analyse syntaxique.
#
En outre, je présente les notions d'origine pour donner du sens et de l'unicité
aux entités topologiques. Je présente aussi une méthode exploitant les chemins
pour maintenir une origine dans un contexte qui ne la décrit/maintient pas (explicitement).
*** la création
*** la suppression
*** le non-changement
*** la modification
*** la scission
*** la fusion
*** le sans effet
*** discussion sur les règles repliées
*  Réévaluation à base de règles de transformation de graphe
Ici, je présente tout d'abord un fil rouge.

Ensuite, je présente un mécanisme pour le nommage persistant des brins et orbites dans les G-cartes.
#
Enfin, je montre en quoi c'est nécessaire et utile pour réévaluer une spécification paramétrique.

Dans ce chapitre, je reprends le narratif utilisé pour ma présentation au R-GTMG.
**  Spécification paramétrique
Ici, je présente une spécification paramétrique et son édition/sa modification.
**** Une identification des opérations
**** Des paramètres géométriques
**** Des paramètres topologiques
** Nommage persistant des brins
Mise en place d'un mécanisme de nommage à base de règles de transformation de graphe
Ce mécanisme comprend, pour chaque brin, l'ensemble des paires (numéro application, nom de nœud) qui conduisent à sa création/le réécrivent.
** Nommage persistant des orbites
Combinaison d'orbites d'origine et de suivi dans un DAG pour une représentation
complète d'un évènement à chaque application de règles. Formalisation de l'usage
de chemins pour préciser une origine lorsque celle-ci n'est pas directement liée
à un nœud d'accroche dans une règle.
** Réévaluation
Ici, je présente la méthode de réévaluation.
#
J'explique que je fais ça à partir du nom persistant d'une orbite (arbre
d'évaluation) et ce pour chacune des orbites identifiées dans la spec à
réévaluer.
*** Construction à partir d'un DAG d'évaluation
(du début jusqu'à la fin)
Puisque les DAGs de réévaluation sont utilisés pour l'appariement de paramètres
topologiques, ceux-ci ne contiennent non pas des nœuds de règles, mais des brins
issus de l'objet en cours de reconstruction.
*** Stratégies de réévaluation
- Scission d'un paramètre topologique : évaluation de tout ou partie des paramètres éligibles
- Suppression d'un paramètre topologique : interruption de la réévaluation pour ce paramètre (potentiellement de l'objet)
*  Réévaluer des scripts de règles pour générer des modèles complexes (En cours)
Ici, je présente l'adaptation de la méthode pour les scripts Jerboa.
#
Les scripts sont des outils puissants permettant d'organiser règles dans combinaisons de structures de contrôles.
#
J'explique qu'actuellement, on supporte des scripts comportant les combinaisons à base de trois type de structures de contrôle :
- les séquences (du plus simple)
- les boucles de sous-orbites d'une orbite (au)
- les conditions If-Then-Else sur les opérations (plus compliqué)
** Les séquences de règles
- Extension de la spécification paramétrique : des blocs « séquence » de règles contenues dans un script
- Extension des DAGs : une boîte englobante contenant les règles jouées dans le contexte d'un script
** Les boucles de sous-orbites
- Extension de la spécification paramétrique : des blocs « boucle » de règles contenues dans une boucle de script
- Extension des DAGs : Ajout de branches pour identifier les paramètres topologiques itérés dans une boucle
** Les conditions Si-Sinon-Alors
- Extension de la spécification paramétrique : des blocs « condition » de règles contenues dans une condition de script
- Extension des DAGs : Ajout d'un paramètre associé à boîte permettant d'identifier une instance de cellule topologique (spécifique aux règles Jerboa)
** Exemples (Scripts avec combinaisons de structures)
Ici, je montre quelques exemples de scenarii avec et sans combinaisons.
** Discussion
Discussion des structures de contrôles qui n'apparaissent pas ici, boucles plus générales (while, …)
*  Implantation d'un système de modélisation à base de règles de transformation de graphe
Ici, je présente productions (implantations et design) liés aux travaux présentés jusque-là.
** spécification paramétrique
Ici, on retrouve les structures de données suivantes :
- ParametricSpecification
- Application
- PersistentName
- PersistentIDElement
** Nommage persistant des brins
Ici, on a l'algorithme pour la construction et l'« héritage » des noms persistant des brins.
** Nommage persistant des orbites (Arbres de jeu) et appariement (arbres de rejeu)
Ici, on a les algorithmes pour créer les arbres d'évaluation et de réévaluations:
- HistoryRecord (refactoring prévu pour l'appeler EvaluationTree)
- ReevaluationTree
** Visualisation des arbres de jeu et de rejeu
Ici, je présente le pipeline pour faire le rendu visuel des arbres (pas la peine de présenter les scripts dans leur intégralité, si (?))
** Interface Utilisateur pour éditer et générer des spécifications paramétriques
Ici, je présente l'interface graphique conçue et développée par Tom pour faire
l'édition des spécifications paramétriques directement dans le viewer Jerboa (s'il a le
temps de la finir, sinon dire que c'est fait à la main en éditant un json)
*  État de l'art
- de Luca, Stefani, …
*  Extension de la spécification paramétrique pour annoter avec des données temporelles
** Annotation des opérations avec des données temporelles
** Modulation de la vitesse d'animation en fonction des deltas temporels entre deux opérations
*  Processus d'animation de modèle générés automatiquement
** Génération à la volée des modèles ?
** Pré-génération des modèles avant phase d'animation ?
*  Conclusions
