#+title:
#+author:

* titre
Bonjour, je m'appelle Maxime Gaide et aujourd'hui, je vous fais un exposé de mes travaux sur la réévaluation de modèle basée sur les règles de transformation de graphe
* slide 1
La réévaluation est un mécanisme de reconstruction un objet par la
ré-application des opérations d'une spécification paramétrique.

Suivons un exemple :
- Une première opération, à droite, crée la face f1 avec son arête e1 à gauche
- La suivante extrude f1 en un cube et e1 en la face f2
- On triangule f2 et créons f7
- Pour la colorer.

Maintenant, éditons cette spécification paramétrique et réévaluons la pour
obtenir un objet différent.

On ajoute l'opération qui insert un sommet l'arête e1.

- La face f1 et l'arête e1 sont recréées
- Le sommet inséré scinde e1 en e5 et e6
- L'extrusion, s'applique sur f1 mais cette fois e5 et e6 sont extrudés en f3 et f4.

Se pose la question de comment poursuivre la réévaluation puisque f2 et f7
n'existent plus sous leur forme initiale.

On se confronte ici à la nécessité d'identifier des cellules avec des noms persistants.

* plan
- L'objectif de mes travaux est de permettre la réévaluation de spécifications
  éditées notamment avec l'ajout, la suppression et le déplacement d'opérations.
- Pour cela nous utilisons deux formalismes
  - Celui des cartes généralisées pour les objets
  - Celui des règles Jerboa de transformation de graphe pour les opérations de modélisation
- Notre contribution comprend :
  - d'une part un mécanisme de nommage persistant basé sur les règles Jerboa
  - d'autre part un mécanisme de réévaluation exploitant ce nommage persistant

* plan - formalismes

Commençons avec les cartes généralisées pour la représentation des objets

* 3
** 3.1
Ici, un objet
** 3.2
Il se décompose en deux volumes connectés par des 3-liaisons vertes
** 3.3
Les volumes en faces connectés par des 2-liaisons bleues
** 3.4
Les faces en arêtes connectés par des 1-liaisons rouges
** 3.5
Les arêtes en sommets connectés par des 0-liaisons noires

Il s'agit d'un graphe dont les nœuds sont appelés des brins.
* 4
Dans ces graphes, les cellules sont représentées par des sous-graphes par exemple:
** 4.1
Le sommet incident au brin a contient a, tous les brins atteignables des liaisons 1, 2 et 3 ainsi que ces liaisons
** 4.2
Cette arête contient ceux atteignable par des liaisons 0,2 et 3
** 4.3
Ici la face pour les liaisons 0,1,3
** 4.4
Le volume 0,1,2
** 4.5
Et nous pouvons représenter toutes sortes d'entité topologique comme cette arête de volumes.

Ces sous-graphes sont appelés des orbites

* 5
** 5.1
Passons maintenant aux règles Jerboa pour transformer des objets et prenons l'exemple de la triangulation
** 5.2
Une règle se présente ainsi
** 5.3
Le nœud n0, à gauche, est étiqueté du type face. Appliqué sur a0, il filtre cette face.
** 5.4
À gauche, n0 et ses brins sont préservés mais les 1-liaisons sont supprimés d'où le tiret du bas
** 5.5
n2 est un nœud créé, ses brins sont créés par copie de ceux de n0. Les liaisons sont renommées de 0,1,3 à 1,2,3 respectivement.
** 5.6
Enfin, n1 est créé, les liaisons 0 et 1 sont renommés en tiret du bas et 2 respectivement.
** 5.7
Les nœuds sont étiquetés par des arcs implicites
** 5.8
et sont connectés par des arcs explicites
** 5.9
On peut représenter des orbites dans les règles.

Par exemple la face de volume incidente à n0.

À gauche, elle contient n0 et ses arcs 0, 1

À droite, elle contient n0 ses arcs 0, l'arc 1 qui le connecte a n1, l'arc 0 qui
connecte n1 à n2 et les arcs 1 de n2.

Notons que s'il y a une seule orbite face dans la règle, il y en a bien 4 dans l'objet.
Cela est dû au renommage des 1-arcs dans la règle qui ne sont ni 0 ni 1.

On peut voir que les arcs 0 et 1 à droite sont des renommages du 0-arc à gauche.
Chaque face a pour origine une arête préservée.

Grâce à une analyse statique en pré-calcul des règles, on est capable de
détecter tout type d'évènement sur les orbites indépendamment des objets.

* Plan Nommage Persistant
Nous avons fini pour les formalismes, passons maintenant au mécanisme de nommage persistant

Reprenons notre exemple de l'introduction
* 7
** 7.1
La première règle qui s'affiche crée une face dont deux brins.
Le brin 3 est créé par le nœud n3 et le brin 6 par n6
** 7.1
L'extrusion s'applique sur la face incidente au brin identifié par [1n6] 1n3
devient 1n3;2n1 et 1n6 devient 1n6;2n1
Les brin 33 et 35 sont des copies du brin 3, leurs identifiants sont 1n3;2n2 et 1n3;2n4 respectivement.
** 7.1
La triangulation s'applique sur 1n3;2n2 et l'identifiant de 35 devient 1n3;2n4;3n0
** 7.1
Enfin la coloration s'applique 1n3;2n4;3n0 qui devient 1n3;2n4;3n0;4n0

Nous venons de dérouler un mécanisme de nommage persistant pour les brins
